import { GameConfig } from "./types";

export const GAMES_CONFIG: { [key: string]: GameConfig } = {
  TruthOrDare: {
    id: "TruthOrDare",
    title: "Truth or Dare",
    emoji: "🤫",
    description: "AI generates hilarious dares and deep secrets. Uncover the truth or perform wild dares together.",
    minPlayers: 2,
    maxPlayers: 6,
    rounds: 5,
    actionDurationSeconds: 30,
    difficulty: "Easy",
  },
  Quiz: {
    id: "Quiz",
    title: "AI Quiz",
    emoji: "🧠",
    description: "Compete in custom generated trivia questions based on trending esports, tech, or pop-culture topics.",
    minPlayers: 2,
    maxPlayers: 6,
    rounds: 5,
    actionDurationSeconds: 15,
    difficulty: "Medium",
  },
  StoryBuilder: {
    id: "StoryBuilder",
    title: "Story Builder",
    emoji: "📝",
    description: "Write one sentence at a time. AI combines sentences into a dramatic, read-aloud narrative.",
    minPlayers: 2,
    maxPlayers: 6,
    rounds: 4,
    actionDurationSeconds: 25,
    difficulty: "Easy",
  },
  Drawing: {
    id: "Drawing",
    title: "Guess the Drawing",
    emoji: "🎨",
    description: "Draw AI-assigned prompts on screen. Other players vote on who captured the prompt best.",
    minPlayers: 2,
    maxPlayers: 6,
    rounds: 3,
    actionDurationSeconds: 45,
    difficulty: "Hard",
  },
  Reaction: {
    id: "Reaction",
    title: "Reaction Challenges",
    emoji: "⚡",
    description: "Press the trigger instantly when the indicator lights up. Tests real-time esports reaction speeds.",
    minPlayers: 2,
    maxPlayers: 6,
    rounds: 5,
    actionDurationSeconds: 10,
    difficulty: "Hard",
  },
  WouldYouRather: {
    id: "WouldYouRather",
    title: "Would You Rather",
    emoji: "🤔",
    description: "Hard choices curated by AI. Vote on extreme scenarios and see who agrees with you.",
    minPlayers: 2,
    maxPlayers: 6,
    rounds: 5,
    actionDurationSeconds: 20,
    difficulty: "Easy",
  },
  NeverHaveIEver: {
    id: "NeverHaveIEver",
    title: "Never Have I Ever",
    emoji: "🥂",
    description: "Confess to funny actions. Tap if you are guilty, while the AI tallies and judges the player status.",
    minPlayers: 2,
    maxPlayers: 6,
    rounds: 5,
    actionDurationSeconds: 15,
    difficulty: "Easy",
  },
};
