"use client";

import React from "react";
import { Box, Container, Typography, Stack } from "@mui/material";
import { motion } from "framer-motion";
import SportsEsportsIcon from "@mui/icons-material/SportsEsports";
import AutoAwesomeIcon from "@mui/icons-material/AutoAwesome";
import GroupsIcon from "@mui/icons-material/Groups";
import SecurityIcon from "@mui/icons-material/Security";
import { Button, Card } from "@/components/ui";
import { useAppNavigation } from "@/hooks/use-app-navigation";

const GAMES_PREVIEW = [
  { title: "Truth or Dare", emoji: "🤫", desc: "AI-generated deep secrets and hilarious dares." },
  { title: "AI Quiz", emoji: "🧠", desc: "Esports, pop-culture and custom AI trivia showdowns." },
  { title: "Guess Drawing", emoji: "🎨", desc: "Draw assignment prompts and let players vote." },
  { title: "Story Builder", emoji: "📝", desc: "Collaborative sentence stitching read aloud by AI." },
];

export default function LandingPage() {
  const { navigate } = useAppNavigation();

  return (
    <Box sx={{ minHeight: "100vh", backgroundColor: "#0B0F14", py: { xs: 4, md: 8 } }}>
      <Container maxWidth="lg">
        {/* Top Navbar */}
        <Box display="flex" justifyContent="space-between" alignItems="center" mb={{ xs: 6, md: 10 }}>
          <Box display="flex" alignItems="center" gap={1}>
            <SportsEsportsIcon sx={{ color: "#22C55E", fontSize: 32 }} />
            <Typography variant="h6" fontWeight={900} letterSpacing="-0.03em">
              PARTYVERSE <span style={{ color: "#22C55E" }}>AI</span>
            </Typography>
          </Box>
          <Button variant="outlined" color="primary" onClick={() => navigate("/login")}>
            Sign In
          </Button>
        </Box>

        {/* Hero Section */}
        <Box sx={{ display: "flex", flexDirection: { xs: "column", md: "row" }, gap: 4, alignItems: "center", mb: 10 }}>
          <Box sx={{ width: { xs: "100%", md: "58.3%" } }}>
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
            >
              <Typography
                variant="h2"
                component="h1"
                fontWeight={900}
                sx={{
                  fontSize: { xs: "2.5rem", md: "4rem" },
                  lineHeight: 1.1,
                  mb: 2,
                }}
              >
                Play Unlimited <br />
                <span style={{ color: "#22C55E" }}>AI Party Games</span> Together.
              </Typography>
              
              <Typography variant="h6" sx={{ color: "#9CA3AF", fontWeight: 500, mb: 4, maxWidth: "550px" }}>
                Create rooms, invite friends, and dive into fixing answers, drawings, and reaction games dynamically generated by AI.
              </Typography>

              <Stack direction={{ xs: "column", sm: "row" }} spacing={2}>
                <Button variant="contained" color="primary" size="large" onClick={() => navigate("/register")}>
                  Create Free Account
                </Button>
                <Button variant="outlined" color="secondary" size="large" onClick={() => navigate("/login")}>
                  Browse Public Rooms
                </Button>
              </Stack>
            </motion.div>
          </Box>

          <Box sx={{ width: { xs: "100%", md: "41.7%" } }}>
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.8, delay: 0.2 }}
            >
              <Box
                sx={{
                  position: "relative",
                  width: "100%",
                  height: "380px",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                }}
              >
                <Box
                  sx={{
                    position: "absolute",
                    width: "280px",
                    height: "280px",
                    backgroundColor: "rgba(34, 197, 94, 0.05)",
                    borderRadius: "50%",
                    filter: "blur(60px)",
                    zIndex: 0,
                  }}
                />
                
                {/* Floating Preview Cards */}
                <Box sx={{ display: "flex", flexWrap: "wrap", gap: 2, width: "100%", position: "relative", zIndex: 1 }}>
                  {GAMES_PREVIEW.map((g, idx) => (
                    <Box key={g.title} sx={{ width: "calc(50% - 8px)", boxSizing: "border-box" }}>
                      <motion.div
                        animate={{ y: [0, -10, 0] }}
                        transition={{
                          duration: 4,
                          repeat: Infinity,
                          delay: idx * 0.5,
                          ease: "easeInOut",
                        }}
                      >
                        <Card sx={{ p: 2, height: "160px", display: "flex", flexDirection: "column", justifyContent: "space-between" }}>
                          <Typography variant="h4">{g.emoji}</Typography>
                          <Box>
                            <Typography variant="subtitle2" fontWeight={800} sx={{ mb: 0.5 }}>
                              {g.title}
                            </Typography>
                            <Typography variant="caption" sx={{ color: "#9CA3AF", display: "block" }}>
                              {g.desc}
                            </Typography>
                          </Box>
                        </Card>
                      </motion.div>
                    </Box>
                  ))}
                </Box>
              </Box>
            </motion.div>
          </Box>
        </Box>

        {/* Feature Cards Grid */}
        <Box sx={{ mb: 10 }}>
          <Typography variant="h4" align="center" fontWeight={900} mb={6}>
            PLATFORM FEATURES
          </Typography>
          
          <Box sx={{ display: "flex", flexDirection: { xs: "column", sm: "row" }, gap: 4 }}>
            <Box sx={{ width: { xs: "100%", sm: "33.3%" } }}>
              <Card sx={{ p: 4, height: "100%" }}>
                <AutoAwesomeIcon sx={{ color: "#22C55E", fontSize: 40, mb: 2 }} />
                <Typography variant="h6" fontWeight={800} mb={1}>
                  AI-Powered Content
                </Typography>
                <Typography variant="body2" sx={{ color: "#9CA3AF" }}>
                  Fixed game frameworks, but unlimited content generated in real-time by state-of-the-art AI models.
                </Typography>
              </Card>
            </Box>

            <Box sx={{ width: { xs: "100%", sm: "33.3%" } }}>
              <Card sx={{ p: 4, height: "100%" }}>
                <GroupsIcon sx={{ color: "#3B82F6", fontSize: 40, mb: 2 }} />
                <Typography variant="h6" fontWeight={800} mb={1}>
                  Real-time Multiplayer
                </Typography>
                <Typography variant="body2" sx={{ color: "#9CA3AF" }}>
                  Instantly synchronize player moves, voting rounds, chats, and typing notifications using Socket.IO.
                </Typography>
              </Card>
            </Box>

            <Box sx={{ width: { xs: "100%", sm: "33.3%" } }}>
              <Card sx={{ p: 4, height: "100%" }}>
                <SecurityIcon sx={{ color: "#EF4444", fontSize: 40, mb: 2 }} />
                <Typography variant="h6" fontWeight={800} mb={1}>
                  Capacitor PWA Ready
                </Typography>
                <Typography variant="body2" sx={{ color: "#9CA3AF" }}>
                  Built with responsive mobile-first layouts so it compiles directly to iOS/Android apps with Capacitor.
                </Typography>
              </Card>
            </Box>
          </Box>
        </Box>

        {/* Footer */}
        <Box sx={{ borderTop: "1px solid rgba(255, 255, 255, 0.08)", pt: 4, textAlign: "center" }}>
          <Typography variant="caption" sx={{ color: "#9CA3AF" }}>
            © 2026 PartyVerse AI. Designed like a premium AAA esports platform. All rights reserved.
          </Typography>
        </Box>
      </Container>
    </Box>
  );
}

